/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OrcunDemirHomework1;

import java.util.*;

public class App {
    public static ArrayList<String> search(ArrayList<String> names, Integer minLength, Integer maxLength,
            String search) {
        ArrayList<String> res = new ArrayList<String>();
        for (String str : names) {
            if (str.length() >= minLength && str.length() <= maxLength
                    && str.toLowerCase().indexOf(search.toLowerCase()) != -1) {
                res.add(str);
            }
        }
        return res;
    }

    public static void main(String[] args) {
        ArrayList<String> list = new ArrayList<>();
        list.add("Zomado");
        list.add("Mamadollahulazzim");
        list.add("Orci");
        list.add("Mamado");
        System.out.println(search(list, 4, 101, "masdfdo"));
    }
}
