/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OrcunDemirHomework1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test
    public void testEmptyList() {
        ArrayList<String> list = new ArrayList<>();
        assertEquals(new ArrayList<String>(), App.search(list, 0, 101, "a"));
    }

    @Test
    public void testTooBigMinLength() {
        ArrayList<String> list = new ArrayList<>(Arrays.asList("Alperen", "Ahmet", "Arda"));
        assertEquals(new ArrayList<String>(), App.search(list, 101, 121, "a"));
    }

    @Test
    public void testTooSmallMaxLength() {
        ArrayList<String> list = new ArrayList<>(Arrays.asList("Alperen", "Ahmet", "Arda"));
        assertEquals(new ArrayList<String>(), App.search(list, 1, 3, "a"));
    }

    @Test
    public void testValidLimits() {
        ArrayList<String> list = new ArrayList<>(Arrays.asList("Alperen", "Ahmet", "Arda"));
        assertEquals(new ArrayList<String>(Arrays.asList("Ahmet", "Arda")), App.search(list, 3, 6, "a"));
    }

    @Test
    public void testNotFound() {
        ArrayList<String> list = new ArrayList<>(Arrays.asList("Alperen", "Ahmet", "Arda"));
        assertEquals(new ArrayList<String>(), App.search(list, 3, 6, "someText"));
    }

}
